#!/bin/bash
#Wrire is a little script that creates a latex writting setup. By default, it creates a "report" folder filled with a "rep.tex" file template and its correspondent "rep.pdf" file.

#Additional arguments can be given to wrire:
#   img: creates an "img" folder inside the report folder.
#   bib: creates a bibliografia.bib template.

#The arguments are fed simply by adding the words after the command. For example, to create the report and img folders and the .bib file, you should execute "wrire img bib".
#--------------------------------------------------------------------
[ -e report ] && echo "Ya existe un directorio \"report\"." || mkdir report


for i in "$*"
do
    if [ "$i" = "img" ]
    then
        [ -e report/img ] && echo "Ya existe un directorio \"img\", omitiendo esta opción." || mkdir report/img
    elif [ "$i" = "bib" ]
    then
        [ -e report/bibliografia.bib ] && echo "Ya existe un fichero \"bibliografia.bib\", omitiendo esta opción." || cp /home/diego/.vim/snippets/latex/bibtex.bib report/bibtex.bib
    else
        echo "No se ha reconocido el argumento \"${i}\""
    fi
done
