#!/bin/bash
#Wrire is a little script that creates a latex writting setup. By default, it creates a "report" folder filled with a "rep.tex" file template and its correspondent "rep.pdf" file.

#Additional arguments can be given to wrire:
#   img: creates an "img" folder inside the report folder.
#   bib: creates a bibliografia.bib template.

#The arguments are fed simply by adding the words after the command. For example, to create the report and img folders and the .bib file, you should execute "wrire img bib".
#--------------------------------------------------------------------
MSG1="Directorio \"report\" presente, no se duplicará." 
MSG2="Directorio \"img\" presente, omitiendo opción \"img\"."
MSG3="Fichero \"bibliografia.bib\" presente, omitiendo opción \"bib\"."
MSG4="Argumento \"${i}\" no reconocido."
DIR1="/home/diego/.config/nvim/snippets/latex/"
[ -e report ] && echo || mkdir report && cp "${DIR1}init.tex" report/report.tex; cp "${DIR1}init.pdf" report/report.pdf


for i in "$*"
do
    if [ "$i" = "img" ]
    then
        [ -e report/img ] && echo $MSG2 || mkdir report/img
    elif [ "$i" = "bib" ]
    then
        [ -e report/bibliografia.bib ] && echo $MSG3 || cp "${DIR1}bibtex.bib" report/bibtex.bib
    else
        echo $MSG4
    fi
done
